apiVersion: v1
kind: Service
metadata:
  name: k8intel-api-service
spec:
  type: LoadBalancer 
  selector:
    app: k8intel-api
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 8080 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8intel-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8intel-api
  template:
    metadata:
      labels:
        app: k8intel-api
    spec:
      containers:
      - name: k8intel-api-container
        # IMPORTANT: Replace 'your-acr-name' with the real name of your Azure Container Registry
        # The ':latest' tag is just a placeholder; the pipeline will replace the whole image definition.
        image: kk8intelregistrynmac.azurecr.io/k8intel-api:latest 
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: k8intel-secrets 
              key: db-connection-string
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: k8intel-secrets
              key: jwt-key
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: k8intel-secrets
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: k8intel-secrets
              key: jwt-audience
---
# --- Example Kubernetes Secret ---
# You would save this as 'k8s-secrets.yml', fill in the base64-encoded values,
# and apply it ONCE to your cluster manually: kubectl apply -f k8s-secrets.yml
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: k8intel-secrets
# type: Opaque
# data:
#   db-connection-string: "UG9zdGdyZVN1cGVyU2VjcmV0Q29ubmVjdGlvblN0cmluZw==" # echo -n 'PostgreSuperSecretConnectionString' | base64
#   jwt-key: "VGhpcyBJcyBNeSBWZXJ5IFNlY3VyZSBKV1QgS2V5IGZvciBIMjU2"
#   jwt-issuer: "SzhJbnRlbEFQSQ=="
#   jwt-audience: "SzhJbnRlbENsaWVudA=="