using System;
using System.ComponentModel.DataAnnotations;

namespace K8Intel.Models
{
    public enum RecommendationType { Cost, Stability }

    // Represents an actionable suggestion generated by the system
    public class Recommendation
    {
        public int Id { get; set; }
        public int ClusterId { get; set; }
        [Required]
        public RecommendationType Type { get; set; }
        [Required]
        public string Message { get; set; } = string.Empty;
        public string Severity { get; set; } = "Medium"; // Low, Medium, High
        public string TargetResource { get; set; } = string.Empty; // e.g., "Deployment/my-app"
        public DateTime GeneratedAt { get; set; }
        public Cluster Cluster { get; set; }
    }
}